### ISSUE TITLE
Port Forwarding bug - Value Error in __main__.py

### ISSUE THREAD

**Issue by lorenzo149** [GianisTsol/python-p2p#6]
`Discovering routers...
Traceback (most recent call last):
  File "C:\Users\benin\OneDrive\Documenti\GitHub\python-p2p\pythonp2p\__main__.py", line 4, in <module>
    new = Node("", PORT, FILE_PORT)  # start the node
  File "C:\Users\benin\OneDrive\Documenti\GitHub\python-p2p\pythonp2p\node.py", line 152, in __init__
    portforwardlib.forwardPort(port, port, None, None, False, "TCP", 0, "", True)
  File "C:\Users\benin\OneDrive\Documenti\GitHub\python-p2p\pythonp2p\portforwardlib.py", line 240, in forwardPort
    status, message = open_port(
  File "C:\Users\benin\OneDrive\Documenti\GitHub\python-p2p\pythonp2p\portforwardlib.py", line 177, in open_port
    conn = http.client.HTTPConnection(parsedurl.hostname, parsedurl.port)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '57970None'`

**Comment by GianisTsol** [comment]
Provide more info. Python version. How can I recreate this?
